### PR TITLE
Oehmsmith

### PR DESCRIPTION
**Pull request by oehm-smith**
Refer to the https://github.com/TypedProject/tsed-example-passport-azure-ad/blob/master/readme.md now for latest information.

----

Work done to implement SPA (Angular7 here) with TSED using Azure AD for authentication.  Thus the purpose of this is to be hosted in Azure though due to the configuration, this will run locally (on developer machine) and continue to consult Azure AD for Auth.

Some notes:

Azure - set up the App as per:
* https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration
* **This should be done as part of this work**

Azure - create App Registration
* `Azure > App Registrations > THE_APP > Expose an API` to create scopes (roles).  
* Add it to the app under `Azure > App Registrations > THE_APP > API Permissions`

Azure - set to use version 2 of token:
* `Azure > App > App Active Directory > App Registrations > Manifest` - set accessTokenAcceptedVersion=2

ClientId, TenantId - set these for client and server to the same values but in different locations:
* Client - add to the environment files - see https://blog.angulartraining.com/how-to-manage-different-environments-with-angular-cli-883c26e99d15
* Server - for Local Development add them to a `.env` file in the root of the project
** On Azure add them as Application Settings

Roles - the scopes for an application need to be assigned to Users or Groups they belong to
* https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/methods-for-assigning-users-and-groups

There is an Azure developer's blog post on all this at https://joonasw.net/view/defining-permissions-and-roles-in-aad.

### CODE REVIEW

**Comment by oehm-smith** [comment]
Hi @Romakita could you help me out here.  I will have to paste the code here as I'm having troubles (due to the network) pushing the code (I will do it tonight my time when I get home, so it might be available when you get to this).

I have the following Controller code.  Do you know of a way to abstract this first part about testing if `request.method === head`?  Pretty much everything apart from `return {text: "Hello world"};`

 ```typescript
   @Get("/hello-world")
    @OAuthBearer({"scopes": ["tester"]})
    helloWorld(@Req() request: Express.Request, @Res() response: Express.Response) {
        const scopes = request.ctx.endpoint.get(OAuthBearerOptions) || {"scopes": []};
        console.log(`helloWorld - request method: ${request.method}`);
        console.log(`====> check endpoint scopes: ${scopes}, ${JSON.stringify(scopes)}, ${typeof scopes}`);
        response.setHeader("Access-Control-Expose-Headers", "scopes");
        response.setHeader("scopes", JSON.stringify(scopes));
        if (request.method.toUpperCase() === "HEAD") {
            // we don't want to do any of the possibly intensive work if all this is is a HEAD request,
            // especially if the authorisation at the given scope is required
            console.log(`helloWorld - HEAD so end early`);
            response.end();
            // return;
        }
        return {text: "Hello world"};
    }

```

**Comment by Romakita** [comment]
Strange. Head request should not call your endpoint...

Here some suggestion improvement :)
```typescript
 
   @Get("/hello-world")
   @OAuthBearer({"scopes": ["tester"]})
   helloWorld(@OAuthScopes() scopes: string[] /* OR @OAuthParams("scopes") scopes: string[]*/, @Req() req: Req) {
       return {text: "Hello world"};
   }
```

Update OAuthBearer implementation to add automatically the scopes headers on the response and prevent HEAD request:
```typescript
export function OAuthBearer(options: any = {}): Function {
    const authFn = (req: any, res: any, next: any) => {
        console.log(`authFn  - options: ${JSON.stringify(options)}`);
        return Passport.authenticate("oauth-bearer", {session: false, ...options})(req, res, next);
    };
    return applyDecorators(
        AuthOptions(OAuthBearerOptions as any, options), // Add this to store all options and retrieve it in verify function
        UseAuth(authFn as any),

        // Metadata for swagger
        Security("oauth", ...(options.scopes || [])),
        Operation({
            "parameters": [
                {
                    "in": "header",
                    "name": "Authorization",
                    "type": "string",
                    "required": true
                }
            ]
        }),
        Responses(401, {description: "Unauthorized"}),
        Responses(403, {description: "Forbidden"}),
        UseBefore((request, response, next) => {
           const {scopes = []} = request.ctx.endpoint.get(OAuthBearerOptions) || {}

           response.set("Access-Control-Expose-Headers", "scopes")
           response.set("scopes", JSON.stringify(scopes));

           if (request.method.toUpperCase() === "HEAD") { // prevent head request and skip endpoint
               return response.send()
           }
           
           next()
        })
    );
}
```


Here decorators implementation
```typescript
@Filter()
export class OAuthScopesFilter {
   transform(expression, request, response){
       const {scopes = []} = request.ctx.endpoint.get(OAuthBearerOptions) || {}
       return scopes
   }
}
// OR
@Filter()
export class OAuthParamFilter {
   constructor(private parseService: ParseService){}
   transform(expression, request, response){
       const options = request.ctx.endpoint.get(OAuthBearerOptions) || {}
       return parseService.eval(expression, options)
   }
}
// DECORATORS
export function OAuthScopes() {
   return UseFilter(OAuthScopesFilter, {
    expression,
    useType,
    useConverter: false,
    useValidation: false,
    paramType: "AUTH"
  });
}
// OR
export function OAuthParams(expression) {
  return UseFilter(OAuthParamFilter, {
    expression,
    useType,
    useConverter: false,
    useValidation: false,
    paramType: "AUTH"
  });
}
```

Nice job @oehm-smith :D
See you ;)
Romain

**Comment by oehm-smith** [comment]
I decided to keep it simple and explicit.  I've pushed the code now that you can checkout.  I am happy for you to review and suggest changes before it is merged.  For that change I just did:

```
@Controller("/rest")
export class HelloWorldCtrl {
    @Get("/hello-auth-world")
    @OAuthBearer({"scopes": ["tester"]})
    helloAuthScopesWorld(@Req() request: Express.Request, @Res() response: Express.Response) {
        AuthControllerUtils.handleAuthentication(request, response);
        return {text: "hello world with scopes"};
    }
    ...
}

export class AuthControllerUtils {
    static handleAuthentication(@Req() request: Express.Request, @Res() response: Express.Response) {
        const scopes = request.ctx.endpoint.get(OAuthBearerOptions) || {"scopes": []};
        console.log(`helloWorld - request method: ${request.method}`);
        console.log(`====> check endpoint scopes: ${scopes}, ${JSON.stringify(scopes)}, ${typeof scopes}`);
        response.setHeader("Access-Control-Expose-Headers", "scopes");
        response.setHeader("scopes", JSON.stringify(scopes));
        if (request.method.toUpperCase() === "HEAD") {
            // we don't want to do any of the possibly intensive work if all this is is a HEAD request,
            // especially if the authorisation at the given scope is required
            console.log(`helloWorld - HEAD so end early`);
            response.end();
            // return;
        }
    }
}
```

**Comment by oehm-smith** [comment]
I will consider your suggestions after I stew over them for a day or two :).  I might not get back to this immediately as my contract finishes in 2 days and before leaving I need to implement this work for them, deploy to Azure and train people in what I've setup.  Given this I'm happy for you to update the documentation - perhaps just some minimal changes to make people aware that TSED is fully capable on AzureAD.

**Comment by Romakita** [comment]
Yes no problem @oehm-smith ;)

**Comment by Romakita** [comment]
After merging your PR, I'll implement the suggestion for you :). I just need help to know if the code work with azure (I haven't environment to test that).

**Comment by oehm-smith** [comment]
> I haven't environment to test that

Yes and it will become much more difficult for me as I'll lose access to my current Azure account.  It might require the next person who comes along and uses this to do any further testing, bug fixes and additional functionality.

**Comment by oehm-smith** [comment]
Ooops, I realise that i need this for POST also.  But HEAD only works with GET.  Any ideas for how to implement the 'pre-flight' which is in `AuthControllerUtils.handleAuthentication(request, response)`?

**Comment by oehm-smith** [comment]
To get this done, I just added a HEAD for each POST.  Maybe using OPTIONS would be better but I haven't got time for that.  I've pushed my changes.

**Comment by Romakita** [comment]
@oehm-smith I'll review you PR ASAP. Great job :)

**Comment by Romakita** [comment]
@oehm-smith I worked on you branch and change the architecture to have an example ready to use in production (I guess :p)

Can you review change and tell me if you see something strange :)

Great job ;)

**Comment by Romakita** [comment]
I added:
- proxy configuration for the client in dev mode
- splitted package.json => one for client and one for server
- a main package.json to run install, build, start and test for all projects
- a travis.yml

**Comment by Romakita** [comment]
After merging, I would like to provide a basic ui (like vue-cli) and when it's down I'll add this example to tsed.io !

**Comment by oehm-smith** [comment]
Thanks Romakita, I've ended my contract and have been lying a little low and will continue to do so for a couple more days.  I hope to get back to it afterwards and try and setup AzureAD using a personal account so can test it properly.

And yes love the idea of different clients.  The implementation I used for Angular is generic and should port easily.

**Pull request merged**
